# Generated by Django 5.1.2 on 2024-11-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.TextField()),
                ("first_name", models.TextField()),
                ("street_num", models.IntegerField()),
                ("street_name", models.TextField()),
                ("apt_num", models.IntegerField()),
                ("zip_code", models.IntegerField()),
                ("birthday", models.TextField()),
                ("registration_date", models.TextField()),
                ("party", models.TextField()),
                ("precinct_num", models.IntegerField()),
                ("v20_state", models.BooleanField()),
                ("v21_town", models.BooleanField()),
                ("v21_primary", models.BooleanField()),
                ("v22_general", models.BooleanField()),
                ("v23_town", models.BooleanField()),
                ("voter_score", models.IntegerField()),
            ],
        ),
    ]
