# Generated by Django 5.1.3 on 2024-11-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voter_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="apt_num",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="precinct_num",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v20_state",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v21_primary",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v21_town",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v22_general",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v23_town",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="voter_score",
            field=models.TextField(),
        ),
    ]
