# Generated by Django 5.1.3 on 2024-11-22 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clothes",
            name="category",
        ),
        migrations.RemoveField(
            model_name="outfit",
            name="top",
        ),
        migrations.RemoveField(
            model_name="outfit",
            name="shoes",
        ),
        migrations.RemoveField(
            model_name="sell",
            name="item",
        ),
        migrations.RemoveField(
            model_name="outfit",
            name="outerwear",
        ),
        migrations.RemoveField(
            model_name="outfit",
            name="bottom",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Sell",
        ),
        migrations.DeleteModel(
            name="Clothes",
        ),
        migrations.DeleteModel(
            name="Outfit",
        ),
    ]
