# Generated by Django 5.1.3 on 2024-12-09 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0011_closet_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="outfit",
            name="closet",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.closet",
            ),
        ),
    ]
