# Generated by Django 5.1.3 on 2024-12-09 03:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0012_outfit_closet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outfit",
            name="closet",
        ),
    ]
