# Generated by Django 5.1.2 on 2024-10-21 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mini_fb", "0004_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image_file",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="image",
            name="status_message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mini_fb.statusmessage"
            ),
        ),
    ]
